import React from 'react';
import { useTelemetry } from '../context/TelemetryContext';
import { FileText, Download } from 'lucide-react';

export const ReportsView: React.FC = () => {
  const { incidents, showToast } = useTelemetry();

  const handleExportReport = () => {
    showToast('IncidentIQ SRE Reliability & SLA Report exported cleanly.');
  };

  return (
    <div className="space-y-6">
      
      {/* Report Header Card */}
      <div className="p-6 rounded-2xl bg-white border border-slate-200 shadow-xs flex flex-wrap items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-black text-slate-900 flex items-center gap-2">
            <FileText className="w-5 h-5 text-blue-600" />
            <span>SRE Incident & System Reliability Post-Mortem Report</span>
          </h2>
          <p className="text-xs text-slate-500 mt-1 font-medium">
            Generated by IncidentIQ Intelligence Engine for System Administrator (S. Anderson)
          </p>
        </div>

        <button
          onClick={handleExportReport}
          className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-extrabold text-xs transition-colors shadow-md shadow-blue-600/20"
        >
          <Download className="w-4 h-4" />
          <span>Export SRE PDF Report</span>
        </button>
      </div>

      {/* SLA Metric Summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-1">
          <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block">Service Availability (SLA)</span>
          <span className="text-3xl font-black text-emerald-600 font-mono">99.98%</span>
          <p className="text-[11px] text-slate-500">Exceeds target 99.90% SLA threshold</p>
        </div>

        <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-1">
          <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block">Mean Time to Detect (MTTD)</span>
          <span className="text-3xl font-black text-blue-600 font-mono">1.2 sec</span>
          <p className="text-[11px] text-slate-500">Real-time baseline probe window</p>
        </div>

        <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-1">
          <span className="text-xs font-bold text-slate-400 uppercase tracking-wider block">Mean Time to Remediate (MTTR)</span>
          <span className="text-3xl font-black text-indigo-600 font-mono">4.8 sec</span>
          <p className="text-[11px] text-slate-500">Automated Remediation Engine baseline</p>
        </div>
      </div>

      {/* Incident Post-Mortem Audit Trail Table */}
      <div className="p-6 rounded-2xl bg-white border border-slate-200 shadow-xs space-y-4">
        <h3 className="font-extrabold text-slate-900 text-sm">Historical Incident Audit Trail</h3>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-200 text-slate-400 font-bold uppercase text-[10px] bg-slate-50">
                <th className="p-3">Incident ID</th>
                <th className="p-3">Title</th>
                <th className="p-3">Severity</th>
                <th className="p-3">Status</th>
                <th className="p-3">Confidence</th>
                <th className="p-3">Timestamp</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 font-medium">
              {incidents.length === 0 ? (
                <tr>
                  <td colSpan={6} className="p-6 text-center text-slate-400">
                    No historical incidents logged in active session buffer.
                  </td>
                </tr>
              ) : (
                incidents.map(inc => (
                  <tr key={inc.id} className="hover:bg-slate-50">
                    <td className="p-3 font-mono font-bold text-slate-900">{inc.incidentNumber}</td>
                    <td className="p-3 text-slate-800 font-bold">{inc.title}</td>
                    <td className="p-3">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-extrabold uppercase ${
                        inc.severity === 'CRITICAL' ? 'bg-rose-100 text-rose-800' : 'bg-amber-100 text-amber-800'
                      }`}>
                        {inc.severity}
                      </span>
                    </td>
                    <td className="p-3">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                        inc.status === 'Resolved' ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'
                      }`}>
                        {inc.status}
                      </span>
                    </td>
                    <td className="p-3 font-mono font-bold text-blue-600">{inc.confidenceScore}%</td>
                    <td className="p-3 text-slate-500 font-mono">{inc.timestamp}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
};
